#!/bin/bash

# Configuration
LOG_FILE="/writable/data/scripts/iperf_logs.log"  # Single log file
IPERF_DURATION=120       # Match Iperf test duration in seconds
BUFFER_TIME=360          # Buffer time for Iperf test to run
TOTAL_CYCLE_TIME=1720   # Total cycle time (29 minutes)
MAC_ADDR="client_mac"  # Client MAC address

# Create log directory if it doesn't exist
mkdir -p "$(dirname "$LOG_FILE")"

# Initialize the log file
if [ ! -f "$LOG_FILE" ]; then
    echo "Initializing log file: $LOG_FILE"
        echo -e "================ Iperf Test Logs ================\n" > "$LOG_FILE"
        fi
        
        while true; do
            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
                
                    # Collect logs before Iperf test
                        echo "[$TIMESTAMP] Collecting logs BEFORE Iperf test..."
                            {
                                    echo -e "\n========== BEFORE IPERF TEST [$TIMESTAMP] ==========\n"
                                            echo "Command: date"
                                                    date
                                                            echo "Command: rkscli -c \"get uptime\""
                                                                    rkscli -c "get uptime"
                                                                            echo "Command: athstats -i wifi1 -a 1 -T 10"
                                                                                    athstats -i wifi1 -a 1 -T 10
                                                                                            echo "Command: athstats -i wifi1 -p 1 -T 10"
                                                                                                    athstats -i wifi1 -p 1 -T 10
                                                                                                            echo "Command: wifistats wifi1 0 9"
                                                                                                                    wifistats wifi1 0 9
                                                                                                                            echo "Command: wifistats wifi1 0 10"
                                                                                                                                    wifistats wifi1 0 10
                                                                                                                                            echo "Command: wifistats wifi1 0 1"
                                                                                                                                                    wifistats wifi1 0 1
                                                                                                                                                            echo "Command: wifistats wifi1 0 2"
                                                                                                                                                                    wifistats wifi1 0 2
                                                                                                                                                                            echo "Command: wifistats wifi1 0 40"
                                                                                                                                                                                    wifistats wifi1 0 40
                                                                                                                                                                                            echo "Command: nodestats wifi1 \"$MAC_ADDR\" -m -C"
                                                                                                                                                                                                    nodestats wifi1 "$MAC_ADDR" -m -C
                                                                                                                                                                                                            echo "Command: ifconfig eth1"
                                                                                                                                                                                                                    ifconfig eth1
                                                                                                                                                                                                                            echo "Command: cat /sys/kernel/debug/qca-nss-drv/stats/eth_rx"
                                                                                                                                                                                                                                    cat /sys/kernel/debug/qca-nss-drv/stats/eth_rx
                                                                                                                                                                                                                                            echo "Command: cat /sys/kernel/debug/qca-nss-drv/stats/wifili"
                                                                                                                                                                                                                                                    cat /sys/kernel/debug/qca-nss-drv/stats/wifili
                                                                                                                                                                                                                                                        } >> "$LOG_FILE"
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                # Wait for Iperf test to start and complete
                                                                                                                                                                                                                                                                    echo "[$TIMESTAMP] Waiting for Iperf test to run ($BUFFER_TIME seconds)..."
                                                                                                                                                                                                                                                                        sleep $BUFFER_TIME
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                # Collect logs after Iperf test
                                                                                                                                                                                                                                                                                    echo "[$TIMESTAMP] Collecting logs AFTER Iperf test..."
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                echo -e "\n========== AFTER IPERF TEST [$TIMESTAMP] ==========\n"
                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 1"
                                                                                                                                                                                                                                                                                                                wifistats wifi1 1
                                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 2"
                                                                                                                                                                                                                                                                                                                                wifistats wifi1 2
                                                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 9"
                                                                                                                                                                                                                                                                                                                                                wifistats wifi1 9
                                                                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 10"
                                                                                                                                                                                                                                                                                                                                                                wifistats wifi1 10
                                                                                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 40"
                                                                                                                                                                                                                                                                                                                                                                                wifistats wifi1 40
                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: apstats -r -i wifi1"
                                                                                                                                                                                                                                                                                                                                                                                                apstats -r -i wifi1
                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: apstats -v -i wlan32"
                                                                                                                                                                                                                                                                                                                                                                                                                apstats -v -i wlan32
                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: ifconfig eth1"
                                                                                                                                                                                                                                                                                                                                                                                                                                ifconfig eth1
                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: wifistats wifi1 11 --mac \"$MAC_ADDR\""
                                                                                                                                                                                                                                                                                                                                                                                                                                                wifistats wifi1 11 --mac "$MAC_ADDR"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: apstats -s -m \"$MAC_ADDR\""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                apstats -s -m "$MAC_ADDR"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: nodestats wifi1 \"$MAC_ADDR\""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nodestats wifi1 "$MAC_ADDR"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: cat /sys/kernel/debug/qca-nss-drv/stats/eth_rx"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cat /sys/kernel/debug/qca-nss-drv/stats/eth_rx
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Command: cat /sys/kernel/debug/qca-nss-drv/stats/wifili"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cat /sys/kernel/debug/qca-nss-drv/stats/wifili
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } >> "$LOG_FILE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Wait for the remaining time until the next cycle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                REMAINING_WAIT=$((TOTAL_CYCLE_TIME - BUFFER_TIME - IPERF_DURATION))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "[$TIMESTAMP] Waiting for the next cycle ($REMAINING_WAIT seconds)..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sleep $REMAINING_WAIT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
